# currently must rewrite _all_ the desired rustflags for each target, - they don't stack

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold", "--cfg", "tokio_unstable", "-Z", "threads=8", "-Z", "track-diagnostics"]

[profile.dev]
## Disabling debug info speeds up builds a bit.
#debug = 0
## However, in many cases useful to get a good trace:
debug = true
## Will cost compile time, however
# supposed to be faster than llvm, following Orion on this blindly


[build]
rustc-wrapper = "/usr/bin/sccache"
rustflags = ["-Z", "threads=8"]

[rust]
rustflags = ["-Z", "track-diagnostics"]

[alias]
w = "watch"
a = "add"
u = "update"
m = "machete"
re = "insta review"
tr = "insta test --review"
f = "fix --allow-dirty --allow-no-vcs"
fc = "clippy --fix --allow-dirty"
s = "sweep --recursive --installed" # only leave currently active artifacts

# overriding defaults in favor of cargo-limit alternatives
#b = "lbuild --all-features"
#c = "lcheck --all-features"
#t = "ltest --all-features"
#r = "lrun --all-features"
b = "lbuild"
c = "lcheck"
t = "nextest run"
r = "lrun"

# all deps except package
[profile.dev.package."*"]
opt-level = 3

[profile.dev.package]
v_utils.opt-level = 1
#insta.opt-level = 3
#similar.opt-level = 3
