[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold"] #, "--cfg", "tokio_unstable"]

[profile.dev]
## Disabling debug info speeds up builds a bit.
#debug = 0
## However, in many cases useful to get a good trace:
debug = true
## Will cost compile time, however


[build]
rustc-wrapper = "/usr/bin/sccache"
rustflags = ["-Z", "threads=16"]

[rust]
rustflags = ["-Z", "track-diagnostics"]

[alias]
w = "watch"
a = "add"
u = "update"
m = "machete"
re = "insta review"
tr = "insta test --review"
f = "fix --allow-dirty"
fc = "clippy --fix --allow-dirty"

# overriding defaults in favor of cargo-limit alternatives
b = "lbuild --all-features"
c = "lcheck --all-features"
t = "ltest --all-features"
r = "lrun --all-features"

# all deps except package
[profile.dev.package."*"]
opt-level = 3

[profile.dev.package]
v_utils.opt-level = 1
#insta.opt-level = 3
#similar.opt-level = 3
