--M = {}
--
--
---- Open link in Google in second workspace
--M.HandleURL = function()
--  local url = string.match(vim.fn.getline("."), "[a-z]*://[^ >,;]*")
--  if url ~= "" then
--    print("URL to open: " .. url)
--    --// 'sudo -Hu v' is here because I run nvim as root, and chrome doesn't work from root.
--    --vim.cmd("!sudo -Hu v google-chrome-stable https://gnu.org")
--    vim.cmd('exec "!sudo -Hu v google-chrome-stable \'' .. url .. '\'"')
--    vim.cmd('exec "!swaymsg workspace 2"')
--  else
--    vim.cmd('echo "No URI found in line."')
--  end
--end
--
--vim.api.nvim_set_keymap("n", "gl", [[ <Cmd>lua M.HandleURL()<CR> ]], {})
--vim.api.nvim_set_keymap("v", "gl", [[ <Cmd>lua M.HandleURL()<CR> ]], {})
--
----test https://www.gnu.org
--
