positions_dir = "~/s/g/positions"

[binance]
full_key = { env = "BINANCE_TIGER_FULL_KEY" }
full_secret = { env = "BINANCE_TIGER_FULL_SECRET" }
read_key = { env = "BINANCE_TIGER_READ_KEY" }
read_secret = { env = "BINANCE_TIGER_READ_SECRET" }
